### ISSUE TITLE
Install script fails colorize in macOS with zsh terminal

### ISSUE THREAD

**Issue by hrodrig** [santiago-rodrig/vim-setup#1]
Hi, this setup fails using colors with zsh shell in macOS.... but installation was successful (Y)

remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1401 (delta 0), reused 0 (delta 0), pack-reused 1399
Receiving objects: 100% (1401/1401), 224.05 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (597/597), done.

\e[96mINFO\e[27m\e[0m\e[27m\e[0m: \e[7m
	parsing kana/vim-textobj-entire
\e[27m\e[0m\e[27m\e[0m\e[92mCREATE\e[27m\e[0m\e[27m\e[0m\e[7m
	/Users/......./.vim/pack/textobjects/start/vim-textobj-entire
\e[27m\e[0m\e[27m\e[0m
Cloning into '/Users/......./.vim/pack/textobjects/start/vim-textobj-entire'...
remote: Enumerating objects: 190, done.
remote: Total 190 (delta 0), reused 0 (delta 0), pack-reused 190
Receiving objects: 100% (190/190), 23.06 KiB | 327.00 KiB/s, done.
Resolving deltas: 100% (71/71), done.

\e[96mINFO\e[27m\e[0m\e[27m\e[0m: \e[7m
	the plugin located at /Users/..../.vim/pack/markdown/start/markdown-preview.nvim
	requires a functional yarn installation, once you have yarn, go to that same location
	and execute yarn install

**Comment by santiago-rodrig** [comment]
What do you mean? Oh! I get it, i'll need to use a scripting language
instead...
